from FlagEmbedding import BGEM3FlagModel
import torch
#检查是否有显卡可用
print(torch.cuda.is_available())
#可用的显卡有几张
print(torch.cuda.device_count ())


model = BGEM3FlagModel('BAAI/bge-m3',  use_fp16=True, device='cuda')

'''
sentences_1 = ["What is BGE M3?", "Defination of BM25"]
sentences_2 = ["BGE M3 is an embedding model supporting dense retrieval, lexical matching and multi-vector interaction.",
               "BM25 is a bag-of-words retrieval function that ranks a set of documents based on the query terms appearing in each document"]

# {
#   'colbert': [0.7796499729156494, 0.4621465802192688, 0.4523794651031494, 0.7898575067520142],
#   'sparse': [0.195556640625, 0.00879669189453125, 0.0, 0.1802978515625],
#   'dense': [0.6259765625, 0.347412109375, 0.349853515625, 0.67822265625],
#   'sparse+dense': [0.482503205537796, 0.23454029858112335, 0.2332356721162796, 0.5122477412223816],
#   'colbert+sparse+dense': [0.6013619303703308, 0.3255828022956848, 0.32089319825172424, 0.6232916116714478]
# }

sentences_1 = ["<p>I always check the ______ discounts on the app before ordering takeout.</p>"]
sentences_2 = ["<p>I always check the ______ discounts on the app before ordering takeout.</p>"]

#{
# 'colbert': [1.0],
# 'sparse': [0.361083984375],
# 'dense': [1.0],
# 'sparse+dense': [0.7870280146598816],
# 'colbert+sparse+dense': [0.8722168207168579]
# }
# 要不用dense+colbert去判断英语题目重复？

sentences_1 = ["I always check the ______ discounts on the app before ordering takeout.A.lateB.laterC.latestD.lately","The company pays an attendance ______: if you go 30 days without being late or absent, you will get the money.A.salaryB.wageC.bonusD.tax"]
sentences_2 = ["I always check the ______ discounts on the app before ordering takeout.A.latestB.latestC.latelyD.late","The company pays an attendance ______: if you go 30 days without being late or absent, you will get the money.A.bonusB.taxC.salaryD.wage"]

# {
# 'colbert': [0.9784038066864014, 0.5142658948898315, 0.4819754660129547, 0.9913102984428406],
# 'sparse': [0.378662109375, 0.0024051666259765625, 0.00539398193359375, 0.4873046875],
# 'dense': [0.98681640625, 0.5166015625, 0.5185546875, 0.99560546875],
# 'sparse+dense': [0.7840982675552368, 0.345202773809433, 0.34750112891197205, 0.8261719346046448],
# 'colbert+sparse+dense': [0.8618205189704895, 0.4128280282020569, 0.4012908935546875, 0.892227292060852]
# }
# 改进型 colbert+dense(0.5,0.5)
#{
# 'colbert': [0.9784038066864014, 0.5142658948898315, 0.4819754660129547, 0.9913102984428406],
# 'sparse': [0.378662109375, 0.0024051666259765625, 0.00539398193359375, 0.4873046875],
# 'dense': [0.98681640625, 0.5166015625, 0.5185546875, 0.99560546875],
# 'colbert+dense': [0.9826101064682007, 0.5154337286949158, 0.5002650618553162, 0.9934579133987427]
# }
'''

sentences_1=["字数240；话题：拯救环境In order to save the environment, everybody has a role to play. The perfect __[[1]]__ of someone who knows this well enough is a 70-year-old grandmother, Pat Smith.rubbish and caring for 52 British beaches after she made it her 2018 New Year’s resolution to __[[1]]__ one beach each week. She __[[1]]__ spent her Christmas Day picking up plastic bottles on Trevone Beach.<br/>&nbsp;&nbsp;&nbsp;&nbsp;During her year-long cleanup, Smith was often __[[1]]__ by other volunteers, including her grandchildren, who were determined to help her tidy up beach rubbish. However, some people often __[[1]]__ Smith for doing community service, and to this, she said: “people don’t understand I’ve been doing this __[[1]]__. We should all take responsibility for picking up the rubbish as well as __[[1]]__ we don’t drop rubbish in the first place.”<br/>&nbsp;&nbsp;&nbsp;&nbsp;The environmentally conscious granny has no intention of __[[1]]__ just because 2018 was over. “Cleaning 52 beaches in 2018 was my New Year’s Resolution and it’s finally __[[1]]__,”said Smith. “I won’t stop, as our beaches __[[1]]__ me. I’m driven to try and protect our __[[1]]__ for my children and grandchildren and I will __[[1]]__ doing everything in my power to achieve that. I hope my efforts will help people be more __[[1]]__ of their plastic consumption and recycling habits."
             ,"字数232；话题：善行义举Dave and I had just arrived home from his chemo-treatment (化疗) appointment. I should have noticed him __[[1]]__ the door. When I opened it, he fell sideways out of the car onto the walkway. He lay there, too weak to __[[1]]__ himself. I rushed to help, but he weighed close to two hundred pounds and was just __[[1]]__. The slightest bump (碰撞) caused terrible pain, so this __[[1]]__ would be more than he could bear. I called “Dave.” He didn’t __[[1]]__, and I wondered if he had passed out. I looked around in all directions __[[1]]__.<br/>&nbsp;&nbsp;&nbsp;&nbsp;Just then, a man __[[1]]__, pushing a baby carriage, with two children walking beside him. The man __[[1]]__ the baby carriage safely, gestured the children to wait and stepped forward. He lifted Dave’s arm over his shoulder and put his own arm around Dave’s __[[1]]__ to stabilize him. The two __[[1]]__ for the house. Into the sitting room, slowly and gently, the man __[[1]]__ Dave onto our little sofa. He smiled as Dave tried to __[[1]]__ him and said he was glad to help.<br/>He walked back out to the street where the children stood waiting for him. The little group slowly __[[1]]__. There, in the shining sun, I watched, with __[[1]]__. They were just like angels, emerging from nowhere and helping me __[[1]]__."
             ,"字数：320话题：一对夫妇在江西肿瘤医院旁将早餐摊改造成 “抗癌厨房”，18 年来低价甚至免费为患者家属提供烹饪场地，用善意温暖病患家庭的故事A special kitchen is in a path, next to Jiangxi Cancer Hospital, in Nanchang. Around meal time, three times every day, relatives of the hospital’s patients use the kitchen to cook food for their loved ones. a breakfast stall (摊) run by a husband and a wife, Wan Zuocheng and Xiong Gengxiang. One day, in 2023, a young couple asked if they could use the stove to cook food for their son who had bone cancer He wanted to eat his mother’s cooking while he was in hospital. Wan and Xiong let the young mother use their stove for free. Later on, Wan and Xiong offered their cookers for free, so other families could cook meals for relatives with illness. As words spread, people who had used their cookers began describing the breakfast stall as the “anti-cancer kitchen”. Some even called it the “kitchen of love”.<br/>&nbsp; &nbsp; To let more people cook at the same time, Wan and Xiong have turned their breakfast stall into a large kitchen. People who have used their kitchen really wanted to share the costs. As a result, Wan and Xiong set a price: One yuan to cook a dish or to buy a box of rice, and three yuan to cook soup. Water or seasoning (调味品) is free. For people from poor families, the couple refuse to accept their money.They get up at 4 a.m. every day to prepare. They boil water and cook rice at first. To make it easier for others to use the kitchen, Wan and Xiong would like to clean the kitchen, like sweeping the ground and washing the pans and pots.<br/>&nbsp; &nbsp; Wan and Xiong have run the kitchen for 18 years. But they have never regretted their decision. They always listen to patients’ relatives talking about their experiences. They believe listening to them helps them feel relaxed. Xiong says, “It is the happiest thing to run the kitchen and help others.”"
             ,"字数：225话题：海外唐人街的起源、发展、特点及现状A Chinatown in a big city is always one of the most famous local places of interest. Chinatowns are not only home to a growing number of Chinese people but also have their own special traditions and way of life.<br/>&nbsp; &nbsp; Millions of Chinese left their home country in the past to live abroad. In the past centuries, overseas Chinese were cheap workers. They had jobs in farming, as cooks on ships or as harbour (港口) workers. Foreigners didn’t treat them well and most of them lived a life. In the US thousands of Chinese helped to build the railroads. As a result, Chinatowns were in many cities. When the Chinese arrived in foreign cities, they often lived in the same neighbourhood, where they followed their own traditions and spoke their own language. Many Chinese have become successful businessmen. Today, Chinatowns are not only places of interest in visitors’ eyes, but places where people can get great food, view art and listen to Chinese music. There are many traditional festivals and celebrations in Chinatowns including the Chinese New Year.<br/>&nbsp; &nbsp; The main language in Chinatown is Mandarin (普通话). Shop and street signs are often in two languages. People sell all kinds of things, including handicraft, jewelry and traditional Chinese medicine. There are many famous Chinatowns in the world’s major cities. New work’s Chinatown is the largest in the world."
             ]*20
sentences_2=["字数240；话题：拯救环境In order to save the environment, everybody has a role to play. The perfect __[[1]]__ of someone who knows this well enough is a 70-year-old grandmother, Pat Smith. __[[1]]__ with bags, rubber gloves and a rubbish picker, she spent an entire year __[[1]]__ rubbish and caring for 52 British beaches after she made it her 2018 New Year’s resolution to __[[1]]__ one beach each week. She __[[1]]__ spent her Christmas Day picking up plastic bottles on Trevone Beach.<br/>&nbsp;&nbsp;&nbsp;&nbsp;During her year-long cleanup, Smith was often __[[1]]__ by other volunteers, including her grandchildren, who were determined to help her tidy up beach rubbish. However, some people often __[[1]]__ Smith for doing community service, and to this, she said: “people don’t understand I’ve been doing this __[[1]]__. We should all take responsibility for picking up the rubbish as well as __[[1]]__ we don’t drop rubbish in the first place.”<br/>&nbsp;&nbsp;&nbsp;&nbsp;The environmentally conscious granny has no intention of __[[1]]__ just because 2018 was over. “Cleaning 52 beaches in 2018 was my New Year’s Resolution and it’s finally __[[1]]__,”said Smith. “I won’t stop, as our beaches __[[1]]__ me. I’m driven to try and protect our __[[1]]__ for my children and grandchildren and I will __[[1]]__ doing everything in my power to achieve that. I hope my efforts will help people be more __[[1]]__ of their plastic consumption and recycling habits."
             ,"字数：319话题：围绕 “如何应对和减少粗心错误” 展开，提供心态调整与具体行动方法 Careless mistakes can make you feel worse than big ones, simply because they seem so easy to be avoided. It’s important to remember that everyone makes mistakes from time to time, and that’s okay. However, if you’re making lots of careless mistakes, there are a few simple ways to help you.<br/>&nbsp; &nbsp; Realize that making mistakes is normal.<br/>&nbsp; &nbsp; So if you make a mistake, don’t worry. We are humans and we all make mistakes sometimes. Avoid letting yourself down when you make mistakes. Recently studies have shown that there are two common ways that the brain responds&nbsp; after you’ve made a mistake—one says “Pay attention! ” which is like a wake-up call when you think “What happened and why?” The second way is more like the brain shuts down, notices the useless feedback you give yourself as a threat, and then avoids thinking about it completely. People in the second way are more likely to repeat the same type of mistakes over and over again.<br/>&nbsp; &nbsp; Find out what caused that careless mistake.<br/>&nbsp; &nbsp; Ask yourself why you may make a certain type of mistake. Write down how you can avoid making it in the first place. For example, allow yourself more time to do something, start this earlier, and stay more focused on what you are doing, etc.<br/>&nbsp; &nbsp; Stick to the normal sleeping and eating.<br/>&nbsp; &nbsp; It’s amazing how fast lack of sleep can make people forgettable and cause them to feel stressed, which easily leads to careless mistakes. Try to go to bed and wake up around the same time each day, and eat regular healthy meals around the same time each day.<br/>&nbsp; &nbsp; Tell yourself you will do better next time.<br/>&nbsp; &nbsp; Don’t let a mistake wear you down. There’s no need to be a perfectionist. Don’t make excuses. Everyone makes mistakes. It’s how you mistakes that is important. Simply think about how you can solve the problem and move on."
             ,"A special kitchen is in a path, next to Jiangxi Cancer Hospital, in Nanchang. Around meal time, three times every day, relatives of the hospital’s patients use the kitchen to cook food for their loved ones. <br/>&nbsp; &nbsp; The kitchen was a breakfast stall (摊) run by a husband and a wife, Wan Zuocheng and Xiong Gengxiang. One day, in 2023, a young couple asked if they could use the stove to cook food for their son who had bone cancer He wanted to eat his mother’s cooking while he was in hospital. Wan and Xiong let the young mother use their stove for free. Later on, Wan and Xiong offered their cookers for free, so other families could cook meals for relatives with illness. As words spread, people who had used their cookers began describing the breakfast stall as the “anti-cancer kitchen”. Some even called it the “kitchen of love”.<br/>&nbsp; &nbsp; To let more people cook at the same time, Wan and Xiong have turned their breakfast stall into a large kitchen. People who have used their kitchen really wanted to share the costs. As a result, Wan and Xiong set a price: One yuan to cook a dish or to buy a box of rice, and three yuan to cook soup. Water or seasoning (调味品) is free. For people from poor families, the couple refuse to accept their moneyThey get up at 4 a.m. every day to prepare. They boil water and cook rice at first. To make it easier for others to use the kitchen, Wan and Xiong would like to clean the kitchen, like sweeping the ground and washing the pans and pots. Wan and Xiong have run the kitchen for 18 years. But they have never regretted their decision. They always listen to patients’ relatives talking about their experiences. They believe listening to them helps them feel relaxed. Xiong says,"
             ," A Chinatown in a big city is always one of the most famous local places of interest. Chinatowns are not only home to a growing number of Chinese people but also have their own special traditions and way of life.<br/>&nbsp; &nbsp; Millions of Chinese left their home country in the past to live abroad. In the past centuries, overseas Chinese were cheap workers. They had jobs in farming, as cooks on ships or as harbour (港口) workers. Foreigners didn’t treat them well and most of them lived a life. In the US thousands of Chinese helped to build the railroads. As a result, Chinatowns were in many cities. When the Chinese arrived in foreign cities, they often lived in the same neighbourhood, where they followed their own traditions and spoke their own language. Many Chinese have become successful businessmen. Today, Chinatowns are not only places of interest in visitors’ eyes, but places where people can get great food, view art and listen to Chinese music. There are many traditional festivals and celebrations in Chinatowns including the Chinese New Year.<br/>&nbsp; &nbsp; The main language in Chinatown is Mandarin (普通话). Shop and street signs are often in two languages. People sell all kinds of things, including handicraft, jewelry and traditional Chinese medicine. There are many famous Chinatowns in the world’s major cities. New work’s Chinatown is the largest in the world.字数：230话题：一对夫妇在江西肿瘤医院旁将早餐摊改造成 “抗癌厨房”，18 年来低价甚至免费为患者家属提供烹饪场地"
             ]*20
#'colbert+sparse+dense':
# [0.9260361194610596, 0.49815860390663147, 0.4714002311229706, 0.5021432638168335,
# 0.5122590065002441, 0.5030925869941711, 0.5260757207870483, 0.4889642596244812,
# 0.4899771213531494, 0.46670812368392944, 0.8271204233169556, 0.7621060609817505,
# 0.4682702124118805, 0.43827277421951294, 0.5051188468933105, 0.7706902027130127]
# 判断相似度时，中文占比较高？？（非也，好像是大量文字在判断时，前面部分占比重大）

for s in sentences_1:
    pairs = [[s, t] for t in sentences_2]
    scores = model.compute_score(pairs,
                                 max_passage_length=128,
                                 weights_for_different_modes=[0.5, 0, 0.5])
    print(scores["colbert+sparse+dense"])

